# example yaml config

# using this to store references to Azure ML
aml:
  # subscription_id: "<SUBSCRIPTION_ID>"
  # resource_group_name: "<RESOURCE_GROUP>"
  # workspace_name: "<AML_WORKSPACE_NAME>"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: cpu-orchestrator
    datastore: datastore_orchestrator

  host: 
    compute: cpu-orchestrator
    datastore: datastore_orchestrator
    training_data:
      type: uri_file
      mode: 'download'
      path: azureml://datastores/datastore_orchestrator/paths/federated_learning/mnist_vertical/raw_train_data
    testing_data:
      type: uri_file
      mode: 'download'
      path: azureml://datastores/datastore_orchestrator/paths/federated_learning/mnist_vertical/raw_test_data

  contributors:
    - compute: cpu-silo0-westus
      datastore: datastore_silo0_westus
      training_data:
        type: uri_file
        mode: 'download'
        path: azureml://datastores/datastore_silo0_westus/paths/federated_learning/mnist_vertical/raw_train_data
      testing_data:
        type: uri_file
        mode: 'download'
        path: azureml://datastores/datastore_silo0_westus/paths/federated_learning/mnist_vertical/raw_test_data

# training parameters
training_parameters:
  epochs: 4 # number of epochs per iteration (in-silo training) 
  lr: 1e-3 # learning rate
  batch_size: 128 # batch size