name: mnist_train_conda_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.11
  - pip=20.0
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - pip:
    - azureml-mlflow
    - azure-ai-ml==0.1.0b6
    - pandas
    - torchmetrics