
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_in_silo
version: 0.1.0
display_name: Train (in silo)
type: command
description: Component to train a model within a FL silo.
is_deterministic: true

inputs:
  lr:
    type: number
    description: learning rate
    default: 0.01
    optional: true
  epochs:
    type: integer
    description: total number of epochs for local training
    default: 3
    optional: true
  exclude_vars:
    type: string
    description: list of variables to exclude during model loading
    optional: true
  dataset_name:
    type: uri_folder
    description: the name of the dataset
  analytic_sender_id:
    type: string
    description: id of `AnalyticsSender` if configured as a client component
    optional: true
  iteration_num:
    type: integer
    description: Iteration number
    default: 1
    optional: true
  checkpoint:
    type: uri_folder
    description: a given pre-existing checkpoint
    optional: true
  # metrics_prefix:
  #   type: string
  #   description: Metrics prefix
  #   default: Default-prefix
  #   optional: true
  # batch_size:
  #   type: integer
  #   description: batch size
  #   default: 64
  #   optional: true  

outputs:
  model:
    type: uri_folder
    description: the output checkpoint

code: .

command: >-
  python run.py --dataset_name ${{inputs.dataset_name}} $[[--iteration_num ${{inputs.iteration_num}}]] $[[--checkpoint ${{inputs.checkpoint}}]] --model ${{outputs.model}} $[[--lr ${{inputs.lr}}]] $[[--epochs ${{inputs.epochs}}]] $[[--exclude_vars ${{inputs.exclude_vars}}]] $[[--analytic_sender_id ${{inputs.analytic_sender_id}}]]
  
# $[[--metrics_prefix ${{inputs.metrics_prefix}}]] $[[--batch_size ${{inputs.batch_size}}]]


environment: 
  conda_file: ./conda.yaml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
