apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: defaultinstancetype
spec:
  nodeSelector:
    training_node: my_beefy_node
  resources:
#   https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    limits:
      cpu: 16
      nvidia.com/gpu: 8
      memory: 128Gi
    requests:
      cpu: 8000m
      memory: 8000Mi
