api_version: 3
name: example_project
description: NVIDIA FLARE sample project yaml file

# NOTE: custom section for the AzureML NVFlare component
azureml:
  # specify in which environment to run each NVFlare participant
  environment: azureml:nvflare-pt@latest

participants:

  - name: server-1
    type: server
    org: azureml
    fed_learn_port: 8002
    admin_port: 8003
    # NOTE: each participant needs an azureml_compute
    azureml_compute: cpu-orchestrator

  - name: worker-1
    type: client
    org: azureml
    # NOTE: each participant needs an azureml_compute
    azureml_compute: cpu-silo0-westus

  - name: worker-2
    type: client
    org: azureml
    # NOTE: each participant needs an azureml_compute
    azureml_compute: cpu-silo2-brazilsouth

  # - name: worker-3
  #   type: client
  #   org: azureml
  #   azureml_compute: cpu-silo1-francecentral

# NOTE: below is typical NVFlare, untouched

# The same methods in all builders are called in their order defined in builders section
builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      # config_folder can be set to inform NVIDIA FLARE where to get configuration
      config_folder: config

      # app_validator is used to verify if uploaded app has proper structures
      # if not set, no app_validator is included in fed_server.json
      # app_validator: PATH_TO_YOUR_OWN_APP_VALIDATOR

      # when docker_image is set to a docker image name, docker.sh will be generated on server/client/admin
      # docker_image:

      # download_job_url is set to http://download.server.com/ as default in fed_server.json.  You can override this
      # to different url.
      # download_job_url: http://download.server.com/

      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        # if overseer_exists is true, args here are ignored.  Provisioning
        #   tool will fill role, name and other local parameters automatically.
        # if overseer_exists is false, args in this section will be used and the sp_end_point
        # must match the server defined above in the format of SERVER_NAME:FL_PORT:ADMIN_PORT
        # 
        overseer_exists: false
        args:
          sp_end_point: server-1:8002:8003
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
