# example yaml config

# using this to store references to Azure ML
aml:
  subscription_id: "<SUBSCRIPTION_ID>"
  resource_group_name: "<RESOURCE_GROUP>"
  workspace_name: "<AML_WORKSPACE_NAME>"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: "cpu-cluster"
    datastore: "workspaceblobstore"

  silos:
    - compute: cpu-silo-wus2
      datastore: workspaceblobstore
      training_data_path: "azureml:mnist-train-01:1"
      testing_data_path: "azureml:mnist-test-01:1"
    - compute: cpu-silo-eus2
      datastore: workspaceblobstore
      training_data_path: "azureml:mnist-train-02:1"
      testing_data_path: "azureml:mnist-test-02:1"
    - compute: cpu-silo-weu
      datastore: workspaceblobstore
      training_data_path: "azureml:mnist-train-03:1"
      testing_data_path: "azureml:mnist-test-03:1"

components:
  
# training parameters
training_parameters:
  num_rounds: 2
  epochs: 3
  lr: 0.01
  batch_size: 64
