# EXAMPLE CONFIG FILE

# Follow the instructions in the comments to adapt to your settings.

# References to Azure ML workspace (use cli args to override)
aml:
  subscription_id: "<SUBSCRIPTION_ID>"
  resource_group_name: "<RESOURCE_GROUP>"
  workspace_name: "<AML_WORKSPACE_NAME>"

# Parameters to create the degenerate FL graph
federated_learning:
  silos: # silos are provided as a list, but in this basic example we have just one silo
    - compute: arc-localdisk-4 # name of the attached Azure ML compute for the external silo - you will need to adjust this to match the one you created
      datastore: datastore_st_ext_silo # name of the datastore for the external silo - you will need to adjust this to match the one you created
      local_data_path: /mnt/localdata # the path at which the local data are accessed by the Azure Ml job.
