name: test_env
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pandas~=1.3.0
- scipy~=1.7.0
- numpy~=1.22.0
- pip:
  - matplotlib~=3.5.0
  - psutil~=5.8.0
  - azureml-core==1.50.0
  - azureml-defaults==1.50.0
  - azureml-mlflow==1.50.0
  - azureml-telemetry==1.50.0
  - scikit-learn~=1.0.0
  - joblib~=1.2.0
  - debugpy~=1.6.3
