name: mnist_train_conda_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip=20.0
  - pip:
    - azureml-mlflow
    - azure-ai-ml==0.1.0b6
    - torch==1.12.1 
    - torchvision==0.13.1
    - pandas