name: mnist_conda_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=23.0
  - pytorch=1.13.1
  - torchvision=0.14.1
  - cudatoolkit=11.3
  - pip:
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - opacus==1.3.0
    - tqdm==4.64.1
