
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_in_silo
version: 0.1.0
display_name: Train (in silo)
type: command
description: Component to train a model within a FL silo.
is_deterministic: true

inputs:
  train_data:
    type: uri_folder
    description: the input training data
  test_data:
    type: uri_folder
    description: the input testing data
  checkpoint:
    type: uri_folder
    description: a given pre-existing checkpoint
    optional: true
  lr:
    type: number
    description: learning rate
    default: 0.01
    optional: true
  epochs:
    type: integer
    description: total number of local training rounds
    default: 3
    optional: true
  batch_size:
    type: integer
    description: batch size
    default: 64
    optional: true

outputs:
  model:
    type: uri_folder
    description: the output checkpoint

code: .

command: >-
  python run.py --train_data ${{inputs.train_data}} --test_data ${{inputs.test_data}} $[[--checkpoint ${{inputs.checkpoint}}]] --model ${{outputs.model}} $[[--lr ${{inputs.lr}}]] $[[--epochs ${{inputs.epochs}}]] $[[--batch_size ${{inputs.batch_size}}]]

environment: 
  conda_file: ./conda.yaml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
