name: ccfraud_vertical_pretrain_conda_env
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pip:
    - azureml-core==1.47.0
    - azure-keyvault==4.2.0
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - torchmetrics==0.10.3
    - redis==4.5.1
    - tqdm==4.64.1
