$schema: http://azureml/sdk-2-0/CommandComponent.json
name: traininsilo
version: 0.0.1
display_name: TrainInSilo
type: CommandComponent
description: Mock component for displaying a diagram.
is_deterministic: true

inputs:
  input_01:
    type: AnyDirectory
    description: the input data
    optional: true
  input_02:
    type: AnyDirectory
    description: the input data
    optional: true
  message:
    type: String
    description: the message to display
    default: This is the default message.
    optional: true

outputs:
  results:
    type: AnyDirectory
    description: the output data

command: >-
  python run.py --results {outputs.results} [--message {inputs.message}] [--input_01 {inputs.input_01}] [--input_02 {inputs.input_02}]
environment:
  conda:
    conda_dependencies_file: component_env.yaml
  docker:
    image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04
  os: Linux
