
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_in_silo
version: 0.1.0
display_name: Train (in silo)
type: command
description: Mock component to train a model within a FL silo.
is_deterministic: true

inputs:
  train_data:
    type: uri_folder
    description: the input training data
  test_data:
    type: uri_folder
    description: the input testing data
  checkpoint:
    type: uri_folder
    description: a given pre-existing checkpoint
    optional: true

outputs:
  model:
    type: uri_folder
    description: the output checkpoint

command: >-
  python run.py --train_data ${{inputs.train_data}} --test_data ${{inputs.test_data}} [--checkpoint ${{inputs.checkpoint}}] --model ${{outputs.model}}

environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
