name: ccfraud_train_conda_env
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pip:
    - azure-identity==1.12.0
    - azure-keyvault==4.2.0
    - azureml-mlflow==1.48.0
    - pandas==1.5.3
    - torchmetrics==0.10.3
    - opacus==1.3.0
    - tqdm==4.64.1
