name: ccfraud_train_conda_env
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip=22.2.2
  - pytorch==1.13.0
  - pytorch-cuda=11.6
  - pip:
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - torchmetrics==0.10.3
