# example yaml config

# using this to store references to Azure ML
aml:
  subscription_id: "48bbc269-ce89-4f6f-9a12-c6f91fcb772d"
  resource_group_name: "amit-aml-ws-fl-rg"
  workspace_name: "amit-aml-ws-fl"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: "cpu-cluster"
    datastore: "workspaceblobstore"

  silos:
    - compute: cpu-cluster-silo-1
      datastore: workspaceblobstoresilo1
      training_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/train.csv"
      testing_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/t10k.csv"
    - compute: cpu-cluster-silo-2
      datastore: workspaceblobstoresilo2
      training_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/train.csv"
      testing_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/t10k.csv"
    - compute: cpu-cluster-silo-3
      datastore: workspaceblobstoresilo3
      training_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/train.csv"
      testing_data_path: "https://azureopendatastorage.blob.core.windows.net/mnist/processed/t10k.csv"

# training parameters
training_parameters:
  num_rounds: 2
  epochs: 3
  lr: 0.01
  batch_size: 64
