# example yaml config

# using this to store references to Azure ML
aml:
  subscription_id: "<SUBSCRIPTION_ID>"
  resource_group_name: "<RESOURCE_GROUP>"
  workspace_name: "<AML_WORKSPACE_NAME>"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: "cpu-cluster-orchestrator"
    datastore: "workspaceblobstore"

  silos:
    - compute: cpu-cluster-eastus
      datastore: silo_datatore_eastus_private
      training_data_path: "azureml:mnist-train-eastus:1"
      testing_data_path: "azureml:mnist-test-eastus:1"
    - compute: cpu-cluster-westus
      datastore: silo_datatore_westus_private
      training_data_path: "azureml:mnist-train-westus:1"
      testing_data_path: "azureml:mnist-test-westus:1"
    - compute: cpu-cluster-westus2
      datastore: silo_datatore_westus2_private
      training_data_path: "azureml:mnist-train-westus2:1"
      testing_data_path: "azureml:mnist-test-westus2:1"

# training parameters
training_parameters:
  num_rounds: 2
  epochs: 3
  lr: 0.01
  batch_size: 64
