name: agg_conda_env
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pip:
    - mltable==1.2.0
    - azure-ai-ml==1.5.0
    - pandas==1.5.2