apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: computeinstancetype
spec:
  resources:
    limits:
      cpu: "2"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "4Gi"