name: ccfraud_preprocessing_conda_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pip:
    - azure-identity==1.12.0
    - azure-keyvault==4.2.0
    - azureml-mlflow==1.48.0
    - scikit-learn==1.2.2
    - numpy==1.24.2
    - pandas==1.5.3
