# example yaml config

# using this to store references to Azure ML
aml:
  subscription_id: "<SUBSCRIPTION_ID>"
  resource_group_name: "<RESOURCE_GROUP>"
  workspace_name: "<AML_WORKSPACE_NAME>"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: cpu-orchestrator
    datastore: datastore_orchestrator

  silos:
    - compute: gpu-m60-1-wus
      datastore: datastore_silo0_westus
      training_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTrain.csv
      testing_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTest.csv
    - compute: gpu-m60-1-nus
      datastore: datastore_northus
      training_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTrain.csv
      testing_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTest.csv
    - compute: gpu-m60-1-sus
      datastore: datastore_southus
      training_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTrain.csv
      testing_data:
        type: uri_file
        mode: 'download'
        path: https://publictestdatasets.blob.core.windows.net/creditcardfraud/fraudTest.csv

# training parameters
training_parameters:
  num_of_iterations: 4
  epochs: 10
  lr: 1e-5
  batch_size: 10000
