name: ner_train_conda_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - cudatoolkit=11.3
  - pip:
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - transformers==4.25.1
    - datasets==2.7.1
    - evaluate==0.3.0
    - numpy==1.23.5
    - seqeval==1.2.2
    - opacus==1.3.0
    - tqdm==4.64.1
