name: ccfraud_vertical_upload_data_conda_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=22.2.2
  - pip:
    - azure-identity==1.12.0
    - azure-keyvault==4.2.0
    - azureml-core==1.47.0
    - kaggle==1.5.12
    - scikit-learn==1.1.3
    - numpy==1.23.5
    - pandas==1.3.5
