apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: computeinstancetype
spec:
  nodeSelector:
    agentpool: confcompool
  resources:
    limits:
      cpu: "4"
      memory: "32Gi"
    requests:
      cpu: "2"
      memory: "16Gi"