name: ner_preprocess_conda_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.11
  - pip=20.0
  - pytorch=1.12.1
  - cudatoolkit=11.3
  - pip:
    - azureml-mlflow
    - pandas
    - transformers
    - datasets