# shared inputs for this job
inputs:
  lr: 0.01
  epochs_per_iteration: 3
  batch_size: 64


head:
  compute: azureml:cpu-orchestrator
  inputs:
    foo: bar
  command: >
    ./startup/start.sh
  code: "./prod_00/head"
  environment: nvflare-pt@latest

workers:
  westus:
    inputs:
      name: "westus"
    compute: azureml:cpu-silo0-westus
    command: >
      ./startup/start.sh
    code: "./prod_00/worker-1"
    environment: nvflare-pt@latest

  francecentral:
    inputs:
      name: "eastus"
    compute: azureml:cpu-silo1-francecentral
    command: >
      ./startup/start.sh
    code: "./prod_00/worker-2"
    environment: nvflare-pt@latest

  brazilsouth:
    inputs:
      name: "eastus"
    compute: azureml:cpu-silo2-brazilsouth
    command: >
      ./startup/start.sh
    code: "./prod_00/worker-3"
    environment: nvflare-pt@latest
