name: mnist_conda_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=22.1.2
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - pip:
    - azure-core==1.26.2
    - azureml-core==1.48.0
    - azure-servicebus==7.8.1
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - python-dotenv
