name: mnist_vertical_train_conda_env
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - torchvision=0.13.1
  - pytorch-cuda=11.6
  - pip:
    - azure-servicebus==7.8.1
    - azureml-mlflow==1.48.0
    - pandas==1.5.2
    - redis==4.5.1
