name: pipeline-test

on:
  pull_request:
    branches:
    - main
    - release-sdkv2-iteration-**
    paths:
    - mlops/**
    - examples/components/**
    - examples/pipelines/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - name: azure login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy the demo resources in your resource group
      run: az deployment group create --template-file ./mlops/bicep/open_sandbox_setup.bicep --resource-group ${{ secrets.RESOURCE_GROUP_TMP }} --parameters demoBaseName="fldemoasdf"

    - name: Intall python dependencies
      run: pip install -r examples/pipelines/fl_cross_silo_literal/requirements.txt

    - name: Submit HelloWorld fl_cross_silo_literal pipeline
      run: python examples/pipelines/fl_cross_silo_literal/submit.py --subscription_id ${{ secrets.AZURE_SUBSCRIPTION_ID }} --resource_group_name ${{ secrets.RESOURCE_GROUP_TMP }} --workspace_name ${{ secrets.AML_WORKSPACE_NAME }} --example HELLOWORLD --submit
