name: python

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - release-sdkv2-iteration-02

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - run: pip install black

    - run:  black --check .
      if: github.base_ref
    
    - name: Intall python dependencies
      run: pip install -r examples/pipelines/fl_cross_silo_native/requirements.txt
    
    - name: Validate fl_cross_silo_native pipeline
      run: python examples/pipelines/fl_cross_silo_native/submit.py