name: python

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - releave-sdkv2-mvp # retire once release is merged in main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - run: pip install black

    - run:  black --check .
      if: github.base_ref
