name: python

on:
  push:
    branches:
    - main
    - gargamit/ci-tests
  pull_request:
    branches:
    - main
    - release-sdkv2-iteration-02
    - release-sdkv2-iteration-03

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - run: pip install black

    - run:  black --check .
      if: github.base_ref
    
    - name: Intall python dependencies
      run: pip install -r examples/pipelines/fl_cross_silo_native/requirements.txt
    
    - name: Validate fl_cross_silo_native pipeline
      run: python examples/pipelines/fl_cross_silo_native/submit.py

    - name: Submit HelloWorld fl_cross_silo_native pipeline
      run: python examples/pipelines/fl_cross_silo_native/submit.py --subscription_id ${{ secrets.SUBSCRIPTION_ID }} --resource_group_name ${{ secrets.RESOURCE_GROUP }} --workspace_name ${{ secrets.AML_WORKSPACE_NAME }} --example HELLOWORLD --submit