# example yaml config

# using this to store references to Azure ML
aml:
  # subscription_id: "<SUBSCRIPTION_ID>"
  # resource_group_name: "<RESOURCE_GROUP>"
  # workspace_name: "<AML_WORKSPACE_NAME>"

# federated learning parameters
federated_learning:
  orchestrator:
    compute: "orchestrator-01"
    datastore: "datastore_orchestrator"

  silos:
    - name: silo0
      computes: 
      - silo0-01 # name of the compute for silo X
      datastore: datastore_silo0
      silo_data:
        type: uri_folder
        mode: 'download'
        path: azureml://datastores/datastore_silo0/paths/federated_learning/pneumonia

    - name: silo1
      computes: 
      - silo1-01 # we are repeating over the same config for silo 2
      datastore: datastore_silo1
      silo_data:
        type: uri_folder
        mode: 'download'
        path: azureml://datastores/datastore_silo1/paths/federated_learning/pneumonia

    - name: silo2
      computes: 
      - silo2-01 # we are repeating over the same config for silo 3
      datastore: datastore_silo2
      silo_data:
        type: uri_folder
        mode: 'download'
        path: azureml://datastores/datastore_silo2/paths/federated_learning/pneumonia

# training parameters
training_parameters:
  num_of_iterations: 2
  epochs: 5
  lr: 0.01
